import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { analyze, metadata, IDENTITY, VERSION } from '../src/provider.mjs';
const relations=['PASSES_CALLBACK','INVOKES_TASK','TRIGGERS_RELOAD','UPDATES_STATE','RENDERS_FROM'];
const base=(uri,relation)=>({schema_version:'lsp-trace.provider-collector-request.v1',provider_id:`${IDENTITY}@${VERSION}`,adapter_id:'lsp-trace-observation-adapter@1',session:{session_id:'test',generation:1},seed:{uri},relations:[relation],languages:['go'],frameworks:['source-constrained-synthetic'],document_custody:{workspace_revision:{kind:'git',commit:'326718ae733cb26097bd30246276cecd371a4e79'}},limits:{max_nodes:100,request_timeout_ms:30000}});
test('identity is distinct provisional and explicit-only',()=>assert.deepEqual(metadata,{identity:IDENTITY,version:VERSION,selectable:true,selection:'EXPLICIT_ONLY',evidence_class:'SOURCE_CONSTRAINED_SYNTHETIC',discovery_status:'PROVISIONAL_DISCOVERY',capabilities:{relations,languages:['go'],frameworks:[]}}));
test('all five provider-local relations have exact positive and negative observations',async()=>{const d=await mkdtemp(join(tmpdir(),'scs-'));for(const relation of relations){for(const polarity of ['POSITIVE','NEGATIVE']){const p=join(d,`${relation}-${polarity}.go`);await writeFile(p,`package fixture\n// PROVISIONAL_${relation}_${polarity}\n`);const q=base(pathToFileURL(p).href,relation);const a=await analyze(q),b=await analyze(q);assert.equal(a.authority,'PROVIDER_REPORTED');assert.equal(a.observations.length,polarity==='POSITIVE'?1:0);assert.deepEqual(a,b);}}await assert.rejects(()=>analyze({...base(pathToFileURL(join(d,'x')).href,'INVOKES_TASK'),provider_id:'ember-glint@1'}),/explicit provider identity/);});
