import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import test from 'node:test';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { analyze, metadata, IDENTITY, VERSION } from '../src/provider.mjs';

const commit = '326718ae733cb26097bd30246276cecd371a4e79';
const base = (uri, relation) => ({ schema_version: 'lsp-trace.provider-collector-request.v1', provider_id: `${IDENTITY}@${VERSION}`, adapter_id: 'lsp-trace-observation-adapter@1', session: { session_id: 'test', generation: 1 }, seed: { uri }, relations: [relation], languages: ['typescript'], frameworks: ['source-constrained-synthetic'], document_custody: { workspace_revision: { kind: 'git', commit } }, limits: { max_nodes: 100, request_timeout_ms: 30000 } });
async function runFixture(relation, source) { const directory = await mkdtemp(join(tmpdir(), 'scs-ts-')); const path = join(directory, 'fixture.ts'); await writeFile(path, source); return analyze(base(pathToFileURL(path).href, relation)); }

const invokesPositive = `import type { TaskForAsyncTaskFunction } from 'ember-concurrency';\ndeclare const uploadComplete: TaskForAsyncTaskFunction<object, () => Promise<void>>;\nuploadComplete.perform();\n`;
const reloadPositive = `import Model from '@warp-drive/legacy/model';\nclass UserImportModel extends Model {}\ndeclare const uploads: UserImportModel[];\nfor (const upload of uploads) { upload.reload(); }\n`;

test('identity is distinct provisional-discovery and explicit-only TypeScript', () => assert.deepEqual(metadata, { identity: IDENTITY, version: VERSION, selectable: true, selection: 'EXPLICIT_ONLY', evidence_class: 'SOURCE_CONSTRAINED_SYNTHETIC', discovery_status: 'PROVISIONAL_DISCOVERY', capabilities: { relations: ['PASSES_CALLBACK', 'INVOKES_TASK', 'TRIGGERS_RELOAD', 'UPDATES_STATE', 'RENDERS_FROM'], languages: ['typescript'], frameworks: ['source-constrained-synthetic'] } }));
test('ASSERT_SYNTHETIC_PROVIDER_REJECTS_MARKER_ONLY_CONFUSABLE', async () => { const result = await runFixture('INVOKES_TASK', '// PROVISIONAL_INVOKES_TASK_POSITIVE\nconst markerOnly = true;\n'); assert.equal(result.observations.length, 0, 'marker-only source emitted INVOKES_TASK'); });
test('INVOKES_TASK requires TaskForAsyncTaskFunction→Task→AbstractTask.perform checker identity', async () => { const result = await runFixture('INVOKES_TASK', invokesPositive); assert.equal(result.observations.length, 1); const observation = result.observations[0]; assert.match(observation.from.node_id, /receiver=TaskForAsyncTaskFunction/); assert.match(observation.to.node_id, /package=ember-concurrency@5\.2\.0/); assert.match(observation.to.node_id, /symbol=AbstractTask\.perform/); assert.match(observation.to.node_id, /chain=TaskForAsyncTaskFunction→Task→AbstractTask\.perform/); assert.equal(observation.original_anchor.range.start.line, 2); assert.match(observation.to.node_id, /authority=non-authoritative/); });
test('INVOKES_TASK rejects same spelling, any, unknown, and contradictory receivers', async () => { for (const source of [`class Other { perform() {} }\nnew Other().perform();\n`, `declare const value: any;\nvalue.perform();\n`, `declare const value: unknown;\n// @ts-expect-error unknown receiver\nvalue.perform();\n`, `interface TaskForAsyncTaskFunction { perform(): void }\ndeclare const fake: TaskForAsyncTaskFunction;\nfake.perform();\n`]) { const result = await runFixture('INVOKES_TASK', source); assert.equal(result.observations.length, 0, source); } });
test('TRIGGERS_RELOAD requires UserImportModel and @warp-drive/legacy Model.reload plus collection provenance', async () => { const result = await runFixture('TRIGGERS_RELOAD', reloadPositive); assert.equal(result.observations.length, 1); const observation = result.observations[0]; assert.match(observation.from.node_id, /receiver=UserImportModel/); assert.match(observation.from.node_id, /collection=uploads:UserImportModel\[\]/); assert.match(observation.to.node_id, /package=@warp-drive\/legacy@5\.8\.1/); assert.match(observation.to.node_id, /symbol=Model\.reload/); assert.equal(observation.original_anchor.range.start.line, 3); });
test('TRIGGERS_RELOAD rejects unrelated, any, contradictory, and unsupported collection elements', async () => { const sources = [`class Other { reload() {} }\ndeclare const uploads: Other[];\nfor (const upload of uploads) upload.reload();\n`, `declare const uploads: any[];\nfor (const upload of uploads) upload.reload();\n`, `import Model from '@warp-drive/legacy/model';\nclass UserImportModel extends Model {}\nclass Other extends Model {}\ndeclare const uploads: Other[];\nfor (const upload of uploads) upload.reload();\n`, `import Model from '@warp-drive/legacy/model';\nclass UserImportModel extends Model {}\ndeclare const upload: UserImportModel;\nupload.reload();\n`]; for (const source of sources) { const result = await runFixture('TRIGGERS_RELOAD', source); assert.equal(result.observations.length, 0, source); } });
test('unknown reload receiver fails closed with explicit bounded checker failure', async () => { await assert.rejects(() => runFixture('TRIGGERS_RELOAD', `declare const uploads: unknown[];\nfor (const upload of uploads) upload.reload();\n`), /bounded checker failure/); });
test('source diagnostics fail closed with explicit bounded checker failure', async () => { await assert.rejects(() => runFixture('INVOKES_TASK', `import type { Missing } from 'unresolved-package';\ndeclare const value: Missing;\nvalue.perform();\n`), /bounded checker failure/); });
test('other matrix relations derive from TypeScript AST/checker rather than markers', async () => { const fixtures = { PASSES_CALLBACK: `function consume(callback: () => void) { callback(); }\nfunction handler() {}\nconsume(handler);\n`, UPDATES_STATE: `let state = 0;\nstate = 1;\n`, RENDERS_FROM: `const model = { name: 'Ada' };\nconst rendered = model.name;\n` }; for (const [relation, source] of Object.entries(fixtures)) assert.equal((await runFixture(relation, source)).observations.length, 1, relation); });
test('npm pack contains compiler provenance, config, declarations, and runtime dependency', async () => { const packageRoot = new URL('..', import.meta.url); const output = execFileSync('npm', ['pack', '--dry-run', '--json'], { cwd: packageRoot, encoding: 'utf8' }); const packed = JSON.parse(output)[0]; const paths = new Set(packed.files.map(file => file.path)); for (const path of ['provenance.json', 'tsconfig.json', 'vendor/ember-concurrency/index.d.ts', 'vendor/warp-drive/model.d.ts', 'vendor/warp-drive/private-model.d.ts']) assert.ok(paths.has(path), path); const manifest = JSON.parse(await readFile(new URL('../package.json', import.meta.url))); assert.equal(manifest.dependencies.typescript, '5.9.3'); });
test('explicit provider identity and TypeScript seed are mandatory', async () => { const result = await runFixture('INVOKES_TASK', invokesPositive); const request = base(result.documents[0].original_uri, 'INVOKES_TASK'); await assert.rejects(() => analyze({ ...request, provider_id: 'ember-glint@1' }), /explicit provider identity/); await assert.rejects(() => analyze({ ...request, seed: { uri: request.seed.uri.replace(/\.ts$/, '.go') } }), /TypeScript file seed/); });
