package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
)

const originalBase = "docs/pilot/adr0007/source-text-search-v4"
const firstSuccessorBase = "docs/pilot/adr0007/source-text-search-v4-successor-freeze"
const secondSuccessorBase = "docs/pilot/adr0007/source-text-search-v4-successor2-freeze"
const manifestPath = secondSuccessorBase + "/SUCCESSOR2_MANIFEST.json"
const censusPath = secondSuccessorBase + "/SUCCESSOR2_TOOLING_CENSUS.json"
const envelopePath = secondSuccessorBase + "/SUCCESSOR2_FREEZE.json"

const expectedSchemaVersion = "lsp-trace.adr0007.source-text-search.successor2-freeze-manifest.private.v1"
const expectedEnvelopeSchemaVersion = "lsp-trace.adr0007.source-text-search.successor2-freeze-envelope.private.v1"
const expectedCensusSchemaVersion = "lsp-trace.adr0007.source-text-search.successor2-tooling-census.private.v1"
const expectedStage = "successor2_freeze_candidate"
const expectedStatus = "SOURCE_TEXT_SEARCH_V4_SUCCESSOR2_FREEZE_CANDIDATE"
const expectedSourceHead = "e659f01591dc42a64d4a8adc2508b98f8fafba09"
const originalFreezeRoot = "sha256:01df412bc5cce1e0adb824560fd7e5d2ff7f6c2621c2176062b4a170d763d367"
const originalFreezeDigest = "sha256:197b814ab6796ed35c9f59bfc70e6105ba2048db4556ae4ab6105151fe45bf2e"
const firstSuccessorRoot = "sha256:3dca46f4845400371519f19a7caba600ea11f09151174fcace76f7cdd40ab403"
const firstSuccessorFreezeDigest = "sha256:6a64a5b6f8aa91d23fa6f58ae28c38e66d3c9aa21613e2b5e8bab1bf0974da65"
const finalReviseAgent = "b9b4900e-fbdb-476"
const finalReviseReviewedCommit = "43f0c6149bd608992126c2537d4bac65bf0ff6e9"
const firstSuccessorReviseAgent = "agent82482ff4"
const firstSuccessorReviseReviewedCommit = "e659f01591dc42a64d4a8adc2508b98f8fafba09"
const reviseVerdict = "SOURCE_TEXT_SEARCH_DESIGN_REVISE"

var gitCommitRe = regexp.MustCompile(`^[0-9a-f]{40}$`)
var agentIDRe = regexp.MustCompile(`^(agent[0-9a-f]{8}(?:-[0-9a-f]{3,})?|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{3})$`)

var roots = []string{
	originalBase + "/",
	firstSuccessorBase + "/",
	secondSuccessorBase + "/reviews/",
	"internal/adr0007sourcetextsearchv4private/",
	"internal/adr0007sourcetextsearchv4oracle/",
	"internal/adr0007v4contractvalidator/",
	"cmd/adr0007-source-text-search-v4-contract-validate/",
	"cmd/adr0007-source-text-search-v4-private-check/",
	"cmd/adr0007-source-text-search-v4-private-corpusgen/",
	"cmd/adr0007-source-text-search-v4-private-evaluate/",
	"cmd/adr0007-source-text-search-v4-private-mutations/",
	"cmd/adr0007-source-text-search-v4-private-oracle/",
	"cmd/adr0007-source-text-search-v4-private-oracle-check/",
	"cmd/adr0007-source-text-search-v4-private-oracle-freeze/",
	"cmd/adr0007-source-text-search-v4-private-prefreeze/",
	"cmd/adr0007-source-text-search-v4-successor-freeze/",
	"cmd/adr0007-source-text-search-v4-successor2-freeze/",
	"docs/pilot/adr0007/source-text-search-v3/pinned/sourceadmissionv2/",
}

var exactFiles = []string{"go.mod", "go.sum"}

type Member struct { Path string `json:"path"`; Role string `json:"role"`; Bytes int64 `json:"bytes"`; SHA256 string `json:"sha256"` }
type Manifest struct { SchemaVersion string `json:"schema_version"`; Stage string `json:"stage"`; SourceHead string `json:"source_head"`; OriginalFreezeRoot string `json:"original_freeze_root_sha256"`; OriginalFreezeDigest string `json:"original_freeze_json_sha256"`; FirstSuccessorRoot string `json:"first_successor_root_sha256"`; FirstSuccessorFreezeDigest string `json:"first_successor_freeze_json_sha256"`; AllowedRoots []string `json:"allowed_roots"`; AllowedExactFiles []string `json:"allowed_exact_files"`; ExcludedSelf []string `json:"excluded_self"`; NormativeMemberCount int `json:"normative_member_count"`; NormativeBytes int64 `json:"normative_bytes"`; Members []Member `json:"members"`; OuterRootSHA256 string `json:"outer_root_sha256"` }
type Envelope struct { SchemaVersion string `json:"schema_version"`; Status string `json:"status"`; Stage string `json:"stage"`; Successor2RootSHA256 string `json:"successor2_root_sha256"`; Successor2Manifest string `json:"successor2_manifest"`; Successor2ManifestSHA256 string `json:"successor2_manifest_sha256"`; Successor2Census string `json:"successor2_census"`; Successor2CensusSHA256 string `json:"successor2_census_sha256"`; OriginalFreezeRoot string `json:"original_freeze_root_sha256"`; OriginalFreezeDigest string `json:"original_freeze_json_sha256"`; FirstSuccessorRoot string `json:"first_successor_root_sha256"`; FirstSuccessorFreezeDigest string `json:"first_successor_freeze_json_sha256"`; FinalReviseArtifact string `json:"final_revise_artifact"`; FinalReviseArtifactSHA256 string `json:"final_revise_artifact_sha256"`; FirstSuccessorReviseArtifact string `json:"first_successor_revise_artifact"`; FirstSuccessorReviseArtifactSHA256 string `json:"first_successor_revise_artifact_sha256"`; Authority Authority `json:"authority"` }
type Authority struct { AuthorityLevel int `json:"authority_level"`; Accepted bool `json:"accepted"`; DesignGOSelfIssued bool `json:"design_go_self_issued"`; QualificationExecuted bool `json:"qualification_executed"`; FinalReviseExactVerdict string `json:"final_revise_exact_verdict"`; FinalReviseReviewerAgentID string `json:"final_revise_reviewer_agent_id"`; FinalReviseReviewedGitCommit string `json:"final_revise_reviewed_git_commit"`; FinalReviseResultIdentity string `json:"final_revise_result_identity"`; FinalReviseTaskIdentity string `json:"final_revise_task_identity"`; FirstSuccessorReviseExactVerdict string `json:"first_successor_revise_exact_verdict"`; FirstSuccessorReviseReviewerAgentID string `json:"first_successor_revise_reviewer_agent_id"`; FirstSuccessorReviseReviewedGitCommit string `json:"first_successor_revise_reviewed_git_commit"` }
type Census struct { SchemaVersion string `json:"schema_version"`; Tool string `json:"tool"`; Commands []string `json:"commands"`; SemanticBindings []string `json:"semantic_bindings"`; MutationsAuthorized []string `json:"mutations_authorized"`; MutationTests []string `json:"mutation_tests"` }

func main(){ mode:=flag.String("mode","verify","write|verify|dryrun"); flag.Parse(); m,err:=buildManifest(); if err!=nil{die(err)}; c:=buildCensus(); e,err:=buildEnvelope(m,c); if err!=nil{die(err)}; switch *mode{case "write": if err:=writeJSON(manifestPath,m);err!=nil{die(err)}; if err:=writeJSON(censusPath,c);err!=nil{die(err)}; e,_=buildEnvelope(m,c); if err:=writeJSON(envelopePath,e);err!=nil{die(err)}; fmt.Printf("wrote successor2 root=%s members=%d bytes=%d\n",m.OuterRootSHA256,m.NormativeMemberCount,m.NormativeBytes); case "dryrun": b,_:=json.MarshalIndent(struct{Manifest Manifest `json:"manifest"`; Census Census `json:"census"`; Envelope Envelope `json:"envelope"`}{m,c,e},"","  "); fmt.Println(string(b)); case "verify": if err:=verify(m,c,e);err!=nil{die(err)}; fmt.Printf("SUCCESSOR2 FREEZE OK root=%s manifest=%s census=%s envelope=%s members=%d bytes=%d\n",m.OuterRootSHA256,shaFile(manifestPath),shaFile(censusPath),shaFile(envelopePath),m.NormativeMemberCount,m.NormativeBytes); default: die(fmt.Errorf("unknown mode %q",*mode)) } }
func buildManifest()(Manifest,error){ m:=Manifest{SchemaVersion:expectedSchemaVersion,Stage:expectedStage,SourceHead:expectedSourceHead,OriginalFreezeRoot:originalFreezeRoot,OriginalFreezeDigest:originalFreezeDigest,FirstSuccessorRoot:firstSuccessorRoot,FirstSuccessorFreezeDigest:firstSuccessorFreezeDigest,AllowedRoots:append([]string{},roots...),AllowedExactFiles:append([]string{},exactFiles...),ExcludedSelf:[]string{manifestPath,censusPath,envelopePath}}; paths,err:=collectPaths(); if err!=nil{return m,err}; for _,p:=range paths{ b,err:=os.ReadFile(p); if err!=nil{return m,err}; info,err:=os.Lstat(p); if err!=nil{return m,err}; if info.Mode()&os.ModeSymlink!=0{return m,fmt.Errorf("symlink included: %s",p)}; m.Members=append(m.Members,Member{p,roleFor(p),int64(len(b)),sha(b)}); m.NormativeBytes+=int64(len(b))}; m.NormativeMemberCount=len(m.Members); m.OuterRootSHA256=rootDigest(m.Members); return m,nil }
func buildCensus()Census{ return Census{SchemaVersion:expectedCensusSchemaVersion,Tool:"cmd/adr0007-source-text-search-v4-successor2-freeze",Commands:[]string{"go run ./cmd/adr0007-source-text-search-v4-successor2-freeze -mode write","go run ./cmd/adr0007-source-text-search-v4-successor2-freeze -mode verify"},SemanticBindings:[]string{"original v4 docs/contracts/cases/oracle bytes preserved","first successor namespace preserved byte-identically and bound as predecessor","typed final revise provenance separates agent IDs from 40hex git commits","v4 production package","v4 oracle package","v4 contract validator package","pinned sourceadmissionv2 bytes"},MutationsAuthorized:[]string{"additive successor2 namespace files","additive successor2 verifier command"},MutationTests:[]string{"swap final_revise_reviewer_agent_id with reviewed_git_commit must fail","swap first_successor_revise_reviewer_agent_id with reviewed_git_commit must fail","truncate final_revise_reviewer_agent_id must fail","fake final_revise_reviewed_git_commit 40hex without git object must fail","fake first_successor_revise_reviewed_git_commit 40hex without git object must fail"}} }
func buildEnvelope(m Manifest,c Census)(Envelope,error){ fr:=secondSuccessorBase+"/reviews/SOURCE_TEXT_SEARCH_DESIGN_REVISE.b9b4900e-fbdb-476.json"; pr:=secondSuccessorBase+"/reviews/FIRST_SUCCESSOR_SOURCE_TEXT_SEARCH_DESIGN_REVISE.agent82482ff4.json"; return Envelope{SchemaVersion:expectedEnvelopeSchemaVersion,Status:expectedStatus,Stage:expectedStage,Successor2RootSHA256:m.OuterRootSHA256,Successor2Manifest:manifestPath,Successor2ManifestSHA256:shaFile(manifestPath),Successor2Census:censusPath,Successor2CensusSHA256:shaFile(censusPath),OriginalFreezeRoot:originalFreezeRoot,OriginalFreezeDigest:originalFreezeDigest,FirstSuccessorRoot:firstSuccessorRoot,FirstSuccessorFreezeDigest:firstSuccessorFreezeDigest,FinalReviseArtifact:fr,FinalReviseArtifactSHA256:shaFile(fr),FirstSuccessorReviseArtifact:pr,FirstSuccessorReviseArtifactSHA256:shaFile(pr),Authority:Authority{AuthorityLevel:0,Accepted:false,DesignGOSelfIssued:false,QualificationExecuted:false,FinalReviseExactVerdict:reviseVerdict,FinalReviseReviewerAgentID:finalReviseAgent,FinalReviseReviewedGitCommit:finalReviseReviewedCommit,FinalReviseResultIdentity:"not_available",FinalReviseTaskIdentity:"not_available",FirstSuccessorReviseExactVerdict:reviseVerdict,FirstSuccessorReviseReviewerAgentID:firstSuccessorReviseAgent,FirstSuccessorReviseReviewedGitCommit:firstSuccessorReviseReviewedCommit}},nil }
func collectPaths()([]string,error){ seen:=map[string]bool{}; var out []string; add:=func(p string)error{ clean:=filepath.ToSlash(filepath.Clean(p)); if clean=="."||strings.HasPrefix(clean,"../")||filepath.IsAbs(clean){return fmt.Errorf("path escape: %s",p)}; if clean==manifestPath||clean==censusPath||clean==envelopePath{return nil}; if !allowed(clean){return fmt.Errorf("extra path outside allowed roots: %s",clean)}; if seen[clean]{return fmt.Errorf("duplicate path: %s",clean)}; seen[clean]=true; out=append(out,clean); return nil}; for _,r:=range roots{ if err:=filepath.WalkDir(strings.TrimSuffix(r,"/"),func(p string,d fs.DirEntry,err error)error{ if err!=nil{return err}; if d.Type()&os.ModeSymlink!=0{return fmt.Errorf("symlink under allowed root: %s",filepath.ToSlash(p))}; if d.IsDir(){return nil}; return add(filepath.ToSlash(p))}); err!=nil{return nil,err} }; for _,p:=range exactFiles{ if err:=add(p);err!=nil{return nil,err} }; sort.Strings(out); return out,nil }
func allowed(p string)bool{ for _,r:=range roots{ if strings.HasPrefix(p,r){return true} }; for _,f:=range exactFiles{ if p==f{return true} }; return false }
func roleFor(p string)string{ switch{ case strings.HasPrefix(p,secondSuccessorBase+"/reviews/"): return "successor2_review_evidence"; case strings.HasPrefix(p,"cmd/adr0007-source-text-search-v4-successor2-freeze/"): return "successor2_verifier"; case strings.HasPrefix(p,firstSuccessorBase+"/reviews/"): return "first_successor_review_evidence"; case strings.HasPrefix(p,"cmd/adr0007-source-text-search-v4-successor-freeze/"): return "first_successor_verifier"; case strings.HasPrefix(p,firstSuccessorBase+"/"): return "first_successor_freeze_artifact"; case strings.HasPrefix(p,originalBase+"/contracts/"): return "contract"; case strings.HasPrefix(p,originalBase+"/reviews/"): return "predecessor_review_evidence"; case strings.HasPrefix(p,originalBase+"/cases/"): return "case_raw_source"; case strings.HasPrefix(p,originalBase+"/oracle/")&&strings.HasSuffix(p,".expected.json"): return "oracle_expected"; case strings.HasPrefix(p,originalBase+"/oracle/")&&strings.HasSuffix(p,".validator-bundle.json"): return "oracle_bundle"; case strings.HasPrefix(p,originalBase+"/oracle/"): return "oracle_provenance"; case strings.HasPrefix(p,"internal/adr0007sourcetextsearchv4private/"): return "production_package"; case strings.HasPrefix(p,"internal/adr0007sourcetextsearchv4oracle/"): return "oracle_package"; case strings.HasPrefix(p,"internal/adr0007v4contractvalidator/"): return "contract_validator_package"; case strings.HasPrefix(p,"cmd/adr0007-source-text-search-v4-"): return "v4_command"; case strings.HasPrefix(p,"docs/pilot/adr0007/source-text-search-v3/pinned/sourceadmissionv2/"): return "pinned_sourceadmission_bytes"; case p=="go.mod"||p=="go.sum": return "go_dependency_lock"; default: return "v4_documentation" } }
func verify(m Manifest,c Census,e Envelope)error{ var gm Manifest; if err:=readStrict(manifestPath,&gm);err!=nil{return err}; if !reflect.DeepEqual(gm,m){return errors.New("successor2 manifest mismatch")}; var gc Census; if err:=readStrict(censusPath,&gc);err!=nil{return err}; if !reflect.DeepEqual(gc,c){return errors.New("successor2 census mismatch")}; var ge Envelope; if err:=readStrict(envelopePath,&ge);err!=nil{return err}; wantE,_:=buildEnvelope(m,c); if !reflect.DeepEqual(ge,wantE){return errors.New("successor2 envelope mismatch")}; if shaFile(originalBase+"/FREEZE.json")!=originalFreezeDigest{return errors.New("original FREEZE digest mismatch")}; if shaFile(firstSuccessorBase+"/SUCCESSOR_FREEZE.json")!=firstSuccessorFreezeDigest{return errors.New("first successor FREEZE digest mismatch")}; if err:=checkReviewArtifacts();err!=nil{return err}; for _,x:=range []struct{role string; min int}{{"successor2_review_evidence",2},{"successor2_verifier",1},{"first_successor_freeze_artifact",3},{"first_successor_verifier",1},{"production_package",1},{"oracle_expected",50},{"oracle_bundle",50}}{ if err:=ensureRole(m,x.role,x.min);err!=nil{return err} }; if err:=checkCases();err!=nil{return err}; return compareTriple() }
func checkReviewArtifacts()error{ var fr struct{SchemaVersion string `json:"schema_version"`; Kind string `json:"kind"`; ExactVerdict string `json:"exact_verdict"`; FinalReviseReviewerAgentID string `json:"final_revise_reviewer_agent_id"`; ReviewedGitCommit string `json:"reviewed_git_commit"`; ResultIdentity string `json:"result_identity"`; TaskIdentity string `json:"task_identity"`; Scope map[string]any `json:"scope"`; Authority map[string]any `json:"authority"`}; if err:=readStrict(secondSuccessorBase+"/reviews/SOURCE_TEXT_SEARCH_DESIGN_REVISE.b9b4900e-fbdb-476.json",&fr);err!=nil{return err}; if fr.ExactVerdict!=reviseVerdict||fr.FinalReviseReviewerAgentID!=finalReviseAgent||fr.ReviewedGitCommit!=finalReviseReviewedCommit{return errors.New("final revise artifact identity/verdict mismatch")}; if err:=checkAgentID(fr.FinalReviseReviewerAgentID);err!=nil{return fmt.Errorf("final revise agent: %w",err)}; if err:=checkGitCommit(fr.ReviewedGitCommit);err!=nil{return fmt.Errorf("final revise reviewed commit: %w",err)}; var pr struct{SchemaVersion string `json:"schema_version"`; Kind string `json:"kind"`; ExactVerdict string `json:"exact_verdict"`; ReviewerAgentID string `json:"reviewer_agent_id"`; ReviewedGitCommit string `json:"reviewed_git_commit"`; Scope map[string]any `json:"scope"`; Authority map[string]any `json:"authority"`}; if err:=readStrict(secondSuccessorBase+"/reviews/FIRST_SUCCESSOR_SOURCE_TEXT_SEARCH_DESIGN_REVISE.agent82482ff4.json",&pr);err!=nil{return err}; if pr.ExactVerdict!=reviseVerdict||pr.ReviewerAgentID!=firstSuccessorReviseAgent||pr.ReviewedGitCommit!=firstSuccessorReviseReviewedCommit{return errors.New("first successor revise predecessor identity/verdict mismatch")}; if err:=checkAgentID(pr.ReviewerAgentID);err!=nil{return fmt.Errorf("first successor revise agent: %w",err)}; if err:=checkGitCommit(pr.ReviewedGitCommit);err!=nil{return fmt.Errorf("first successor revise reviewed commit: %w",err)}; return nil }
func checkAgentID(s string)error{ if !agentIDRe.MatchString(s){return fmt.Errorf("not expected agent id syntax %q",s)}; if gitCommitRe.MatchString(s){return fmt.Errorf("agent id has git commit syntax %q",s)}; return nil }
func checkGitCommit(s string)error{ if !gitCommitRe.MatchString(s){return fmt.Errorf("not exact 40hex git commit %q",s)}; cmd:=exec.Command("git","cat-file","-e",s+"^{commit}"); if out,err:=cmd.CombinedOutput();err!=nil{return fmt.Errorf("unresolved git commit %q: %w %s",s,err,out)}; return nil }
func checkCases()error{ b,err:=os.ReadFile(originalBase+"/cases/CASE_MATRIX.json"); if err!=nil{return err}; var rows []struct{ID string `json:"id"`; ExpectedOutcome string `json:"expected_outcome"`}; if err:=json.Unmarshal(b,&rows);err!=nil{return err}; if len(rows)!=50{return fmt.Errorf("case count=%d want 50",len(rows))}; complete,failed:=0,0; for _,r:=range rows{ if r.ExpectedOutcome=="COMPLETE"{complete++}else if r.ExpectedOutcome=="FAILED"{failed++}; if _,err:=os.Stat(originalBase+"/oracle/"+r.ID+".expected.json");err!=nil{return err}; if _,err:=os.Stat(originalBase+"/oracle/"+r.ID+".validator-bundle.json");err!=nil{return err} }; if complete!=21||failed!=29{return fmt.Errorf("case split complete/failed=%d/%d want 21/29",complete,failed)}; return nil }
func compareTriple()error{ b,err:=os.ReadFile(originalBase+"/cases/CASE_MATRIX.json"); if err!=nil{return err}; var rows []struct{ID string `json:"id"`}; if err:=json.Unmarshal(b,&rows);err!=nil{return err}; for _,r:=range rows{ attempt:=originalBase+"/cases/"+r.ID+"/attempt.json"; prod:=run("go","run","./cmd/adr0007-source-text-search-v4-private-evaluate",attempt); exp,err:=os.ReadFile(originalBase+"/oracle/"+r.ID+".expected.json"); if err!=nil{return err}; if !bytes.Equal(bytes.TrimSpace(prod),bytes.TrimSpace(exp)){return fmt.Errorf("production != oracle %s",r.ID)}; der:=run("go","run","./cmd/adr0007-source-text-search-v4-contract-validate",originalBase+"/oracle/"+r.ID+".validator-bundle.json","--derive"); if !bytes.Equal(bytes.TrimSpace(der),bytes.TrimSpace(exp)){return fmt.Errorf("derive != oracle %s",r.ID)} }; return nil }
func ensureRole(m Manifest,role string,min int)error{ n:=0; for _,x:=range m.Members{if x.Role==role{n++}}; if n<min{return fmt.Errorf("role %s count %d < %d",role,n,min)}; return nil }
func writeJSON(path string,v any)error{ b,err:=json.MarshalIndent(v,"","  "); if err!=nil{return err}; b=append(b,'\n'); return os.WriteFile(path,b,0644) }
func readStrict(path string,v any)error{ b,err:=os.ReadFile(path); if err!=nil{return err}; if err:=rejectDuplicateKeys(b);err!=nil{return err}; dec:=json.NewDecoder(bytes.NewReader(b)); dec.DisallowUnknownFields(); if err:=dec.Decode(v);err!=nil{return err}; if dec.Decode(&struct{}{})!=io.EOF{return errors.New("trailing json data")}; return nil }
func rejectDuplicateKeys(b []byte)error{ var walk func(json.RawMessage)error; walk=func(raw json.RawMessage)error{ dec:=json.NewDecoder(bytes.NewReader(raw)); tok,err:=dec.Token(); if err!=nil{return err}; switch d:=tok.(type){case json.Delim: if d=='{'{ seen:=map[string]bool{}; for dec.More(){ kt,err:=dec.Token(); if err!=nil{return err}; k:=kt.(string); if seen[k]{return fmt.Errorf("duplicate key %q",k)}; seen[k]=true; var child json.RawMessage; if err:=dec.Decode(&child);err!=nil{return err}; if err:=walk(child);err!=nil{return err} }; _,err=dec.Token(); return err}; if d=='['{ for dec.More(){ var child json.RawMessage; if err:=dec.Decode(&child);err!=nil{return err}; if err:=walk(child);err!=nil{return err} }; _,err=dec.Token(); return err}}; return nil}; var top json.RawMessage; dec:=json.NewDecoder(bytes.NewReader(b)); if err:=dec.Decode(&top);err!=nil{return err}; if dec.Decode(&struct{}{})!=io.EOF{return errors.New("trailing json data")}; return walk(top) }
func rootDigest(ms []Member)string{ h:=sha256.New(); for _,m:=range ms{fmt.Fprintf(h,"%s\x00%s\x00%d\x00%s\n",m.Path,m.Role,m.Bytes,m.SHA256)}; return "sha256:"+hex.EncodeToString(h.Sum(nil)) }
func sha(b []byte)string{s:=sha256.Sum256(b); return "sha256:"+hex.EncodeToString(s[:])}
func shaFile(path string)string{ b,err:=os.ReadFile(path); if err!=nil{return "sha256:missing:"+path}; return sha(b) }
func run(name string,args ...string)[]byte{ cmd:=exec.Command(name,args...); out,err:=cmd.CombinedOutput(); if err!=nil{die(fmt.Errorf("%s %v failed: %w\n%s",name,args,err,out))}; return out }
func die(err error){fmt.Fprintln(os.Stderr,err); os.Exit(1)}
