#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { chmodSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const here = join(root, 'qualification/caller-project-javascript');
const specification = JSON.parse(readFileSync(join(here, 'cases.v1.json')));
const stable = '/tmp/lsp-trace-caller-project-javascript-qualification';
const workspace = join(stable, 'workspace'), install = join(stable, 'install'), dist = join(stable, 'dist');
const mcp = join(stable, 'lsp-trace-mcp'), fakeLSP = join(stable, 'fake-lsp');
const output = join(root, 'qualification/retained/caller-project-javascript/evidence.v1.json');
const retain = process.argv.includes('--retain');
const sha = value => `sha256:${createHash('sha256').update(value).digest('hex')}`;
const canonical = value => Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}` : JSON.stringify(value);
const normalized = value => { const copy=structuredClone(value); copy.id=0; const fix=x=>{if(x?.request_id)x.request_id='replay-normalized'}; fix(copy.result?.structuredContent); if(copy.result?.content?.[0]?.text){const x=JSON.parse(copy.result.content[0].text);fix(x);copy.result.content[0].text=JSON.stringify(x)} return copy };
function run(command,args,options={}) { const result=spawnSync(command,args,{cwd:root,encoding:'utf8',...options}); if(result.status!==0) throw new Error(`ASSERT_CALLER_JS_COMMAND ${command} ${args.join(' ')}\n${result.stdout}\n${result.stderr}`); return result; }
function call(id,name,args){return {jsonrpc:'2.0',id,method:'tools/call',params:{name,arguments:args}}}
function execute(request,bootstrap){const input=`${JSON.stringify(call(1,'lsp_session_v1_list',{}))}\n${JSON.stringify(request)}\n`;const r=spawnSync(mcp,['--bootstrap-config',bootstrap],{input,encoding:'utf8'});if(r.status!==0)throw new Error(`ASSERT_CALLER_JS_REAL_STDIO exit=${r.status} ${r.stderr}`);const lines=r.stdout.trim().split('\n').map(JSON.parse);if(lines.length!==2)throw new Error(`ASSERT_CALLER_JS_EXACT_RESPONSES got=${lines.length}`);return {response:lines[1],transcript:input+r.stdout+r.stderr}}

rmSync(stable,{recursive:true,force:true}); for(const p of [workspace,install,dist])mkdirSync(p,{recursive:true});
run('go',['build','-trimpath','-o',mcp,'./cmd/lsp-trace-mcp']); run('go',['build','-trimpath','-o',fakeLSP,'./cmd/fake-lsp']);
const packed=run('npm',['pack','--pack-destination',dist,'--silent'],{cwd:join(root,'providers/ember-glint')});
const tarball=join(dist,packed.stdout.trim().split('\n').at(-1));
run('npm',['install','--offline','--ignore-scripts','--prefix',install,tarball]);
const provider=realpathSync(join(install,'node_modules/.bin/ember-glint')); chmodSync(provider,0o755);
const taskDeclaration="export interface TaskInstance<T> extends Promise<T> {}\ninterface AbstractTask<A extends unknown[],T>{ perform(...args:A):T }\nexport interface Task<T,A extends unknown[]> extends AbstractTask<A,TaskInstance<T>> {}\nexport declare function task<T>(callback:()=>Promise<T>):Task<T,[]>;\n";
const reloadDeclaration="export default class Model { reload(): Promise<this>; }\n";
for(const item of specification.cases){const project=join(workspace,item.id);mkdirSync(join(project,'src'),{recursive:true});writeFileSync(join(project,'src/seed.js'),item.source);if(item.variant!=='missing-config')writeFileSync(join(project,'jsconfig.json'),item.variant==='malformed-config'?'{ malformed':JSON.stringify({compilerOptions:{target:'ES2022',experimentalDecorators:true,checkJs:true,allowJs:true,noEmit:true},include:['src/**/*.js']}));if(!item.variant.includes('task-declaration')){const p=join(project,'node_modules/ember-concurrency');mkdirSync(p,{recursive:true});writeFileSync(join(p,'package.json'),JSON.stringify({name:'ember-concurrency',version:'99.0.0-caller',types:'index.d.ts'}));writeFileSync(join(p,'index.d.ts'),taskDeclaration)}else if(item.variant==='wrong-task-declaration'){const p=join(project,'node_modules/ember-concurrency');mkdirSync(p,{recursive:true});writeFileSync(join(p,'package.json'),JSON.stringify({name:'confusable-concurrency',version:'99.0.0-caller',types:'index.d.ts'}));writeFileSync(join(p,'index.d.ts'),taskDeclaration)}if(!item.variant.includes('reload-declaration')){const p=join(project,'node_modules/@warp-drive/legacy');mkdirSync(p,{recursive:true});writeFileSync(join(p,'package.json'),JSON.stringify({name:'@warp-drive/legacy',version:'99.0.0-caller',types:'index.d.ts'}));writeFileSync(join(p,'index.d.ts'),reloadDeclaration)}else if(item.variant==='wrong-reload-declaration'){const p=join(project,'node_modules/@warp-drive/legacy');mkdirSync(p,{recursive:true});writeFileSync(join(p,'package.json'),JSON.stringify({name:'@wrong/legacy',version:'99.0.0-caller',types:'index.d.ts'}));writeFileSync(join(p,'index.d.ts'),reloadDeclaration)}}
run('git',['init','-q'],{cwd:workspace});run('git',['config','user.name','lsp-trace qualification'],{cwd:workspace});run('git',['config','user.email','qualification@example.invalid'],{cwd:workspace});run('git',['add','.'],{cwd:workspace});run('git',['commit','-qm','frozen caller JavaScript qualification'],{cwd:workspace,env:{...process.env,GIT_AUTHOR_DATE:'2000-01-01T00:00:00Z',GIT_COMMITTER_DATE:'2000-01-01T00:00:00Z'}});const commit=run('git',['rev-parse','HEAD'],{cwd:workspace}).stdout.trim();
const providerID='ember-glint@1';const bootstrap=join(stable,'bootstrap.json');writeFileSync(bootstrap,JSON.stringify({version:1,processes:[{alias:'caller-js',profile:{trust_domain:'caller-project-javascript',workspace,profile:'fake-lsp',environment_reference:'qualification'},execution:{path:fakeLSP,directory:workspace}}],providers:[{schema_version:'lsp-trace.bootstrap-provider.v1',identity:providerID,version:'1',protocol:{name:'lsp-trace.provider-observations',version:'1'},execution:{path:provider,directory:dirname(provider)},executable_available:true,conformance_verified:true,capabilities:{relations:['INVOKES_TASK','TRIGGERS_RELOAD'],languages:['glimmer-js'],frameworks:['ember']},limits:{request_bytes:1048576,response_bytes:1048576,protocol_messages:1,stderr_bytes:4096,wall_time_ms:30000,termination_grace_ms:1000}}]}));
const attempts=[];
for(const item of specification.cases)for(const operation of specification.operations)for(let replay=1;replay<=2;replay++){const uri=pathToFileURL(realpathSync(join(workspace,item.id,'src/seed.js'))).href;const args={session_id:'caller-js',generation:1,uri,line:item.source.trimEnd().split('\n').length-1,character:0,relations:[item.relation],providers:[providerID],languages:['glimmer-js'],frameworks:['ember'],workspace_revision:{kind:'git',commit,custody:'CALLER_ASSERTED'},fail_on_unknown_revision:true,max_nodes:100,timeout_ms:30000,request_timeout_ms:30000,...(operation==='incoming'?{max_depth:2}:{start_mode:'at',up_depth:2,down_depth:2})};const request=call(attempts.length+2,`lsp_trace_v1_${operation}`,args);const observed=execute(request,bootstrap);const structured=observed.response?.result?.structuredContent;const text=observed.response?.result?.content?.[0]?.text;const parity=typeof text==='string'&&canonical(JSON.parse(text))===canonical(structured);const graph=structured?.content?JSON.parse(structured.content):null;const domain=structured?.envelope_schema_id?.endsWith('/envelope-domain-error.v1.schema.json');const relations=graph?.relations??[];const outcome=graph?'GRAPH':domain?'DOMAIN_ERROR':'INVALID';const declarationCustody=relations.every(r=>r.to.includes('path=node_modules/')&&/sha256=[0-9a-f]{64}/.test(r.to));const originalCustody=relations.every(r=>r.anchors?.length===1&&r.anchors[0].uri===uri&&r.anchors[0].revision===commit&&r.anchors[0].blob);const valid=parity&&outcome===item.expect&&(outcome!=='GRAPH'||(graph.schema_version==='lsp-trace.graph.v4'&&relations.length===item.count&&relations.every(r=>r.kind===item.relation)&&originalCustody&&declarationCustody))&&(!item.code||structured.code===item.code);attempts.push({id:`${item.id}-${operation}-${replay}`,case:item.id,relation:item.relation,operation,replay,expected:{outcome:item.expect,count:item.count??0,code:item.code??null},observed:{outcome,count:relations.length,code:structured?.code??null},status:valid?'PASS':'FAIL',provider_identity:graph?.provenance?.provider_id??providerID,schemas:{graph:graph?.schema_version??null,domain:structured?.envelope_schema_id??null},parity,original_custody:originalCustody,declaration_custody:declarationCustody,request,response:observed.response,digests:{request:sha(canonical(request)),response:sha(canonical(normalized(observed.response))),transcript:sha(observed.transcript)}})}
for(const item of specification.cases)for(const operation of specification.operations){const pair=attempts.filter(x=>x.case===item.id&&x.operation===operation);if(pair.length!==2||pair[0].digests.response!==pair[1].digests.response)throw new Error(`ASSERT_CALLER_JS_DETERMINISTIC_REPLAY ${item.id}/${operation}`)}
if(attempts.length!==48||attempts.some(x=>x.status!=='PASS'))throw new Error(`ASSERT_CALLER_JS_EXACT_COUNTS_OUTCOMES ${attempts.filter(x=>x.status!=='PASS').map(x=>x.id+':'+JSON.stringify(x.observed)).join(',')}`);
const evidence={schema_version:'lsp-trace.caller-project-javascript.evidence.v1',generated_at:retain?new Date().toISOString():null,source_head:run('git',['rev-parse','HEAD']).stdout.trim(),provider:{identity:providerID,installation:'independent-npm-pack-offline-install',package_digest:sha(readFileSync(tarball)),executable_digest:sha(readFileSync(provider))},transport:{identity:'real-lsp-trace-mcp-stdio',mcp_digest:sha(readFileSync(mcp))},workspace:{commit,custody:'PROVIDER_PROVED'},summary:{case_count:12,operation_count:24,replay_attempt_count:48,pass_count:48},attempts};if(retain){mkdirSync(dirname(output),{recursive:true});writeFileSync(output,JSON.stringify(evidence,null,2)+'\n')}console.log(`PASS ASSERT_CALLER_JS_QUALIFICATION cases=12 operations=24 attempts=48 retained=${retain}`);
