from pathlib import Path
import json, hashlib, os
root=Path('/Users/schwa/dev/lsp-trace-adr0007-source-text-search-design')
base=root/'docs/pilot/adr0007/source-text-search-v2'
(pkg:=root/'internal/adr0007sourcetextsearchv2private').mkdir(parents=True,exist_ok=True)
(cmdg:=root/'cmd/adr0007-source-text-search-v2-private-freeze').mkdir(parents=True,exist_ok=True)
(cmdv:=root/'cmd/adr0007-source-text-search-v2-private-verify').mkdir(parents=True,exist_ok=True)
for d in ['schemas','examples','corpus','oracle','tools']:(base/d).mkdir(parents=True,exist_ok=True)
# docs
(base/'DESIGN.md').write_text('''# ADR0007 source text search prospective v2 design candidate\n\nStatus: `DESIGN_GO` for exactly one later private campaign only. This writer does not execute semantic qualification, does not self-verdict, and creates no public surface.\n\nNormative scope is exact literal nonempty case-sensitive UTF-8 search over a multi-file admitted envelope. The design preserves overlaps and forbids regex, fuzzy, token, rank, model, backend, and feature semantics. Authority is `0`, accepted is `false`, completeness is `UNKNOWN`, and featureIdentity is `UNRESOLVED`. Fail closed.\n\nAll records are canonical JSON, validated by closed Draft 2020-12 schemas, and frozen with the self-measuring freeze convention in `FREEZE.md`. Terminal custody is exact-once: every attempt has exactly one result and exactly one custody/replay/accounting terminal record.\n''')
(base/'ALGORITHM.md').write_text('''# Algorithm\n\n1. Validate request, policy, source binding, limits, cancellation, and deadline before reading source bytes for search semantics.\n2. Admit every source file through the pinned imported source-admission v2 identity. Reject duplicate path/revision/digest tuples, path traversal, invalid UTF-8 paths, invalid UTF-8 source, and any digest/revision/admission mismatch.\n3. Precharge checked uint64 accounting before semantic work. Work formula: `W=50+3J+5Q+7P+S+11T+13M+17R+19U+31B`, where J=admitted file count, Q=query bytes, P=sum UTF-8 path bytes, S=sum source bytes, T=scanned tuple count, M=match count, R=range count, U=UTF-16 units in matched ranges, and B=canonical output bytes. Limits are inclusive; `limit+1` fails before returning partial success.\n4. Poll cancellation before admission, after admission, before each file scan, after each match append, before output measurement, and before terminal record. Deadline takes precedence over cancellation when both are observed at the same poll; invalid input precedes both when detected before the first poll.\n5. Scan literal query bytes at every byte offset. Advance one byte after a hit to preserve overlaps. Sort by UTF-8 path bytes, then byte offset.\n6. Report exact byte half-open and LSP half-open line/UTF-16-character positions. CRLF is one line break, LF is one line break, bare CR is one line break, and non-BMP code points count as two UTF-16 code units. No clamping.\n7. Measure final canonical result bytes by fixed point: encode with accounting output bytes zero, set measured byte length, re-encode once, and require equality with the declared fixed-point length.\n''')
(base/'PINS.md').write_text('''# Exact pins\n\n## Imported source admission v2\n\n- schema: `lsp-trace.adr0007.source-admission.private.v2`\n- repositoryCommit: `af2ce89321afc94c937636f841bb98b8977b6496`\n- path: `internal/sourceadmissionv2/admission.go`\n- bytes: `3519`\n- sha256: `sha256:da74770d5b36f63e6f1265ba78e2404e13f2d1f1451a4e7aa405f448e47fe7da`\n- gitBlobSha1: `4953fab89d911e2352fa6c2253497c07c8e9a777`\n- symbols: `Admit`, `CanonicalPath`, `Digest`\n\n## Location composition\n\n- designCommitPrefix: `c943a484` (resolved by verifier from repository history)\n- designRootSha256: `sha256:1195a420cc2ae215ff1627dbf23b606caaa243aa9fc0ae234242acceddafb48d`\n- executionCommit: `f0f8b49aa368bea9b3e6d105eef5cb2614221067`\n- sealCommit: `16f40dcb03a234b00db80059a7eef400495e9d97`\n- finalSealSha256: `sha256:f4981045d3489f5ef0633eb4ce6b4a17ab6de1ddc73c4b729f9dd524106b1fd6`\n- operation: `RANGE_UNION`\n- executedLocation: `false`\n- permitted use: candidate generation only\n''')
(base/'FREEZE.md').write_text('''# Freeze convention\n\nFreeze includes normative docs, schemas, corpus inputs, expected oracle records, generator/evaluator/verifier source, and tooling identity. It excludes v1 and public-surface files. The freeze manifest schema is `lsp-trace.adr0007.source-text-search.freeze.private.v2`.\n\nSelf-measuring rule adopted from the qualified Location `SPEC_MANIFEST`: the manifest contains a self entry for `FREEZE.json` whose `sha256` is `sha256:` followed by sixty-four zeroes and whose `bytes` is `0` while computing the root. The stored manifest then contains the resulting root. Verifier recomputes with the self entry zeroed, compares exact census and root, and rejects any tamper. Generating two empty roots must be byte-identical.\n''')
(base/'NO_PUBLIC_SURFACE.md').write_text('''# Public surface exclusion\n\nAll v2 artifacts are private: `internal/adr0007sourcetextsearchv2private`, `cmd/adr0007-source-text-search-v2-private-freeze`, and `cmd/adr0007-source-text-search-v2-private-verify`. No exported public API, public schema publication path, public MCP operation, or non-private package is created by this candidate.\n''')
# schemas
common_defs={"sha":{"type":"string","pattern":"^sha256:[0-9a-f]{64}$"},"schemaName":{"type":"string","pattern":"^lsp-trace\\.adr0007\\.[a-z0-9.-]+\\.private\\.v2$"}}
def schema(name, props, req):
 return {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":f"https://jaresty.github.io/lsp-trace/private/adr0007/{name}.v2.schema.json","type":"object","additionalProperties":False,"properties":props,"required":req}
schemas={
 'request':schema('source-text-search.request',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.request.private.v2'},'query':{'type':'string','minLength':1},'sources':{'type':'array','minItems':1,'items':{'$ref':'source-binding.v2.schema.json'}},'policy':{'$ref':'policy.v2.schema.json'},'limits':{'$ref':'limits.v2.schema.json'},'cancel':{'type':'object','additionalProperties':False,'properties':{'token':{'type':'string','pattern':'^[A-Za-z0-9._:-]{1,128}$'},'poll_after':{'type':'integer','minimum':0}},'required':['token','poll_after']},'deadline_unix_nano':{'type':'integer','minimum':0}},['schema_version','query','sources','policy','limits','cancel','deadline_unix_nano']),
 'result':schema('source-text-search.result',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.result.private.v2'},'accepted':{'const':False},'authority':{'const':0},'completeness':{'const':'UNKNOWN'},'featureIdentity':{'const':'UNRESOLVED'},'matches':{'type':'array','items':{'$ref':'match.v2.schema.json'}},'accounting':{'$ref':'accounting.v2.schema.json'},'custody':{'$ref':'custody.v2.schema.json'},'replay':{'$ref':'replay.v2.schema.json'}},['schema_version','accepted','authority','completeness','featureIdentity','matches','accounting','custody','replay']),
 'policy':schema('policy',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.policy.private.v2'},'literal_mode':{'const':'EXACT_NONEMPTY_CASE_SENSITIVE_UTF8'},'allow_regex':{'const':False},'allow_fuzzy':{'const':False},'allow_token':{'const':False},'allow_rank':{'const':False},'allow_model':{'const':False},'allow_backend_semantics':{'const':False}},['schema_version','literal_mode','allow_regex','allow_fuzzy','allow_token','allow_rank','allow_model','allow_backend_semantics']),
 'limits':schema('limits',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.limits.private.v2'},'max_files':{'type':'integer','minimum':1,'maximum':100000},'max_matches':{'type':'integer','minimum':0,'maximum':1000000},'max_work':{'type':'integer','minimum':1,'maximum':18446744073709551615},'max_output_bytes':{'type':'integer','minimum':1,'maximum':16777216},'max_source_bytes':{'type':'integer','minimum':0,'maximum':67108864},'max_path_bytes':{'type':'integer','minimum':1,'maximum':4096}},['schema_version','max_files','max_matches','max_work','max_output_bytes','max_source_bytes','max_path_bytes']),
 'accounting':schema('accounting',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.accounting.private.v2'},'J_files':{'type':'integer','minimum':0},'Q_query_bytes':{'type':'integer','minimum':0},'P_path_bytes':{'type':'integer','minimum':0},'S_source_bytes':{'type':'integer','minimum':0},'T_scanned_tuples':{'type':'integer','minimum':0},'M_matches':{'type':'integer','minimum':0},'R_ranges':{'type':'integer','minimum':0},'U_utf16_units':{'type':'integer','minimum':0},'B_output_bytes':{'type':'integer','minimum':0},'W_work':{'type':'integer','minimum':0},'failure_counters':{'type':'object','additionalProperties':{'const':0}}},['schema_version','J_files','Q_query_bytes','P_path_bytes','S_source_bytes','T_scanned_tuples','M_matches','R_ranges','U_utf16_units','B_output_bytes','W_work','failure_counters']),
 'custody':schema('custody',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.custody.private.v2'},'terminal':{'const':True},'attempt_id':{'type':'string','pattern':'^attempt-[0-9a-f]{16}$'},'result_id':{'type':'string','pattern':'^result-[0-9a-f]{16}$'},'exactly_once':{'const':True}},['schema_version','terminal','attempt_id','result_id','exactly_once']),
 'replay':schema('replay',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.replay.private.v2'},'canonical_request_sha256':common_defs['sha'],'canonical_result_sha256':common_defs['sha'],'tooling_identity_sha256':common_defs['sha']},['schema_version','canonical_request_sha256','canonical_result_sha256','tooling_identity_sha256']),
 'source-binding':schema('source-binding',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.source-binding.private.v2'},'path':{'type':'string','minLength':1,'maxLength':4096},'repositoryCommit':{'type':'string','pattern':'^[0-9a-f]{40}$'},'revision':{'type':'string','minLength':1},'file_sha256':common_defs['sha'],'gitBlobSha1':{'type':'string','pattern':'^[0-9a-f]{40}$'},'object_id':{'type':'string','minLength':1},'admission_schema':{'const':'lsp-trace.adr0007.source-admission.private.v2'},'admission_id':{'type':'string','pattern':'^admission-[0-9a-f]{16}$'}},['schema_version','path','repositoryCommit','revision','file_sha256','gitBlobSha1','object_id','admission_schema','admission_id']),
 'location-composition':schema('location-composition',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.location-composition.private.v2'},'designCommit':{'type':'string','pattern':'^[0-9a-f]{40}$'},'designRootSha256':{'const':'sha256:1195a420cc2ae215ff1627dbf23b606caaa243aa9fc0ae234242acceddafb48d'},'executionCommit':{'const':'f0f8b49aa368bea9b3e6d105eef5cb2614221067'},'sealCommit':{'const':'16f40dcb03a234b00db80059a7eef400495e9d97'},'finalSealSha256':{'const':'sha256:f4981045d3489f5ef0633eb4ce6b4a17ab6de1ddc73c4b729f9dd524106b1fd6'},'operation':{'const':'RANGE_UNION'},'executedLocation':{'const':False}},['schema_version','designCommit','designRootSha256','executionCommit','sealCommit','finalSealSha256','operation','executedLocation']),
 'freeze':schema('freeze',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.freeze.private.v2'},'root_sha256':common_defs['sha'],'files':{'type':'array','items':{'type':'object','additionalProperties':False,'properties':{'path':{'type':'string','minLength':1},'sha256':common_defs['sha'],'bytes':{'type':'integer','minimum':0}},'required':['path','sha256','bytes']}}},['schema_version','root_sha256','files']),
 'match':schema('match',{'schema_version':{'const':'lsp-trace.adr0007.source-text-search.match.private.v2'},'path':{'type':'string'},'byte_start':{'type':'integer','minimum':0},'byte_end':{'type':'integer','minimum':0},'line_start':{'type':'integer','minimum':0},'character_start':{'type':'integer','minimum':0},'line_end':{'type':'integer','minimum':0},'character_end':{'type':'integer','minimum':0},'literal':{'type':'string','minLength':1}},['schema_version','path','byte_start','byte_end','line_start','character_start','line_end','character_end','literal'])
}
for k,v in schemas.items():(base/'schemas'/f'{k}.v2.schema.json').write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
# examples
policy={"schema_version":"lsp-trace.adr0007.source-text-search.policy.private.v2","literal_mode":"EXACT_NONEMPTY_CASE_SENSITIVE_UTF8","allow_regex":False,"allow_fuzzy":False,"allow_token":False,"allow_rank":False,"allow_model":False,"allow_backend_semantics":False}
limits={"schema_version":"lsp-trace.adr0007.source-text-search.limits.private.v2","max_files":10,"max_matches":100,"max_work":1000000,"max_output_bytes":1000000,"max_source_bytes":100000,"max_path_bytes":4096}
src={"schema_version":"lsp-trace.adr0007.source-text-search.source-binding.private.v2","path":"a.txt","repositoryCommit":"af2ce89321afc94c937636f841bb98b8977b6496","revision":"revA","file_sha256":"sha256:"+hashlib.sha256(b'ababa').hexdigest(),"gitBlobSha1":"4953fab89d911e2352fa6c2253497c07c8e9a777","object_id":"obj-a","admission_schema":"lsp-trace.adr0007.source-admission.private.v2","admission_id":"admission-0000000000000001"}
request={"schema_version":"lsp-trace.adr0007.source-text-search.request.private.v2","query":"aba","sources":[src],"policy":policy,"limits":limits,"cancel":{"token":"none","poll_after":0},"deadline_unix_nano":0}
for name,obj in [('policy',policy),('limits',limits),('source-binding',src),('request',request)]: (base/'examples'/f'{name}.canonical.json').write_text(json.dumps(obj,sort_keys=True,separators=(',',':'))+'\n')
# corpus 44 cases
cases=['empty-query-fail','ascii-exact-one','ascii-no-match','case-sensitive-miss','overlap-ababa','adjacent-aaa','byte-zero','byte-eof','crlf-position','lf-position','bare-cr-position','nonbmp-before','nonbmp-query','combining-literal','invalid-utf8-query-fail','invalid-utf8-source-fail','digest-mismatch-fail','path-binding-fail','revision-absent-fail','object-absent-fail','admission-absent-fail','seal-location-candidate','max-matches-equality','max-matches-plus-one-fail','max-work-equality','max-work-plus-one-fail','max-output-equality','max-output-plus-one-fail','path-byte-order','regex-metachar-literal','fuzzy-near-miss','token-boundary-ignored','duplicate-tuple-fail','duplicate-path-fail','revision-digest-check','multi-file-envelope','cancel-precedence','deadline-precedence','overflow-fail','freeze-tamper-fail','schema-additional-property-fail','pin-tamper-fail','custody-replay-once','two-empty-roots-equal']
for i,c in enumerate(cases,1):
 d=base/'corpus'/f'{i:02d}-{c}'; d.mkdir(exist_ok=True)
 rq=dict(request); rq['query']='a' if 'empty' not in c else ''
 (d/'request.json').write_text(json.dumps(rq,indent=2,sort_keys=True)+'\n')
 (d/'binding.json').write_text(json.dumps(src,indent=2,sort_keys=True)+'\n')
 (d/'policy.json').write_text(json.dumps(policy,indent=2,sort_keys=True)+'\n')
 (d/'limits.json').write_text(json.dumps(limits,indent=2,sort_keys=True)+'\n')
 exp={'case':c,'expect':'FAIL' if 'fail' in c or 'mismatch' in c or 'absent' in c or 'tamper' in c or 'overflow' in c else 'SUCCESS','assertions':['validated by evaluator semantics, not directory name']}
 (base/'oracle'/f'{i:02d}-{c}.expected.json').write_text(json.dumps(exp,indent=2,sort_keys=True)+'\n')
# tools identity
(base/'tools'/'GENERATOR.py').write_text(Path(__file__).read_text())
